"""base migration

Revision ID: 98139bb625ab
Revises: 
Create Date: 2025-10-23 17:35:02.200941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98139bb625ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='wannabeaiops'
    )
    op.create_index(op.f('ix_wannabeaiops_users_email'), 'users', ['email'], unique=True, schema='wannabeaiops')
    op.create_index(op.f('ix_wannabeaiops_users_id'), 'users', ['id'], unique=False, schema='wannabeaiops')
    op.create_index(op.f('ix_wannabeaiops_users_username'), 'users', ['username'], unique=True, schema='wannabeaiops')
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['wannabeaiops.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='wannabeaiops'
    )
    op.create_index(op.f('ix_wannabeaiops_chat_sessions_id'), 'chat_sessions', ['id'], unique=False, schema='wannabeaiops')
    op.create_index(op.f('ix_wannabeaiops_chat_sessions_thread_id'), 'chat_sessions', ['thread_id'], unique=False, schema='wannabeaiops')
    op.create_index(op.f('ix_wannabeaiops_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False, schema='wannabeaiops')
    op.create_table('otp_verification',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp_code', sa.String(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['wannabeaiops.users.email'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='wannabeaiops'
    )
    op.create_index(op.f('ix_wannabeaiops_otp_verification_email'), 'otp_verification', ['email'], unique=False, schema='wannabeaiops')
    op.create_index(op.f('ix_wannabeaiops_otp_verification_id'), 'otp_verification', ['id'], unique=False, schema='wannabeaiops')
    op.create_table('chat_transcripts',
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['wannabeaiops.chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='wannabeaiops'
    )
    op.create_index(op.f('ix_wannabeaiops_chat_transcripts_id'), 'chat_transcripts', ['id'], unique=False, schema='wannabeaiops')
    op.create_index(op.f('ix_wannabeaiops_chat_transcripts_thread_id'), 'chat_transcripts', ['thread_id'], unique=False, schema='wannabeaiops')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wannabeaiops_chat_transcripts_thread_id'), table_name='chat_transcripts', schema='wannabeaiops')
    op.drop_index(op.f('ix_wannabeaiops_chat_transcripts_id'), table_name='chat_transcripts', schema='wannabeaiops')
    op.drop_table('chat_transcripts', schema='wannabeaiops')
    op.drop_index(op.f('ix_wannabeaiops_otp_verification_id'), table_name='otp_verification', schema='wannabeaiops')
    op.drop_index(op.f('ix_wannabeaiops_otp_verification_email'), table_name='otp_verification', schema='wannabeaiops')
    op.drop_table('otp_verification', schema='wannabeaiops')
    op.drop_index(op.f('ix_wannabeaiops_chat_sessions_user_id'), table_name='chat_sessions', schema='wannabeaiops')
    op.drop_index(op.f('ix_wannabeaiops_chat_sessions_thread_id'), table_name='chat_sessions', schema='wannabeaiops')
    op.drop_index(op.f('ix_wannabeaiops_chat_sessions_id'), table_name='chat_sessions', schema='wannabeaiops')
    op.drop_table('chat_sessions', schema='wannabeaiops')
    op.drop_index(op.f('ix_wannabeaiops_users_username'), table_name='users', schema='wannabeaiops')
    op.drop_index(op.f('ix_wannabeaiops_users_id'), table_name='users', schema='wannabeaiops')
    op.drop_index(op.f('ix_wannabeaiops_users_email'), table_name='users', schema='wannabeaiops')
    op.drop_table('users', schema='wannabeaiops')
    # ### end Alembic commands ###
